// Generated by scripts/make-voice.mjs — do not edit.
//
// Regenerate after changing the vocabulary in that script; the audio
// files beside it are committed so a build needs no recording tools.
import c40 from "../assets/voice/blank.m4a";
import c45 from "../assets/voice/cells-a-minute.m4a";
import c37 from "../assets/voice/controls.m4a";
import c47 from "../assets/voice/correct.m4a";
import c26 from "../assets/voice/digit-0.m4a";
import c27 from "../assets/voice/digit-1.m4a";
import c28 from "../assets/voice/digit-2.m4a";
import c29 from "../assets/voice/digit-3.m4a";
import c30 from "../assets/voice/digit-4.m4a";
import c31 from "../assets/voice/digit-5.m4a";
import c32 from "../assets/voice/digit-6.m4a";
import c33 from "../assets/voice/digit-7.m4a";
import c34 from "../assets/voice/digit-8.m4a";
import c35 from "../assets/voice/digit-9.m4a";
import c38 from "../assets/voice/dots.m4a";
import c0 from "../assets/voice/letter-a.m4a";
import c1 from "../assets/voice/letter-b.m4a";
import c2 from "../assets/voice/letter-c.m4a";
import c3 from "../assets/voice/letter-d.m4a";
import c4 from "../assets/voice/letter-e.m4a";
import c5 from "../assets/voice/letter-f.m4a";
import c6 from "../assets/voice/letter-g.m4a";
import c7 from "../assets/voice/letter-h.m4a";
import c8 from "../assets/voice/letter-i.m4a";
import c9 from "../assets/voice/letter-j.m4a";
import c10 from "../assets/voice/letter-k.m4a";
import c11 from "../assets/voice/letter-l.m4a";
import c12 from "../assets/voice/letter-m.m4a";
import c13 from "../assets/voice/letter-n.m4a";
import c14 from "../assets/voice/letter-o.m4a";
import c15 from "../assets/voice/letter-p.m4a";
import c16 from "../assets/voice/letter-q.m4a";
import c17 from "../assets/voice/letter-r.m4a";
import c18 from "../assets/voice/letter-s.m4a";
import c19 from "../assets/voice/letter-t.m4a";
import c20 from "../assets/voice/letter-u.m4a";
import c21 from "../assets/voice/letter-v.m4a";
import c22 from "../assets/voice/letter-w.m4a";
import c23 from "../assets/voice/letter-x.m4a";
import c24 from "../assets/voice/letter-y.m4a";
import c25 from "../assets/voice/letter-z.m4a";
import c44 from "../assets/voice/line-done.m4a";
import c42 from "../assets/voice/new-line.m4a";
import c46 from "../assets/voice/percent-accurate.m4a";
import c36 from "../assets/voice/ready.m4a";
import c39 from "../assets/voice/space.m4a";
import c41 from "../assets/voice/try-again.m4a";
import c43 from "../assets/voice/words.m4a";

export const VOICE_CLIPS: Readonly<Record<string, string>> = {
  "letter-a": c0,
  "letter-b": c1,
  "letter-c": c2,
  "letter-d": c3,
  "letter-e": c4,
  "letter-f": c5,
  "letter-g": c6,
  "letter-h": c7,
  "letter-i": c8,
  "letter-j": c9,
  "letter-k": c10,
  "letter-l": c11,
  "letter-m": c12,
  "letter-n": c13,
  "letter-o": c14,
  "letter-p": c15,
  "letter-q": c16,
  "letter-r": c17,
  "letter-s": c18,
  "letter-t": c19,
  "letter-u": c20,
  "letter-v": c21,
  "letter-w": c22,
  "letter-x": c23,
  "letter-y": c24,
  "letter-z": c25,
  "digit-0": c26,
  "digit-1": c27,
  "digit-2": c28,
  "digit-3": c29,
  "digit-4": c30,
  "digit-5": c31,
  "digit-6": c32,
  "digit-7": c33,
  "digit-8": c34,
  "digit-9": c35,
  "ready": c36,
  "controls": c37,
  "dots": c38,
  "space": c39,
  "blank": c40,
  "try-again": c41,
  "new-line": c42,
  "words": c43,
  "line-done": c44,
  "cells-a-minute": c45,
  "percent-accurate": c46,
  "correct": c47,
};
