// Generated file, do not edit.

import { type CharacterDict } from "../types.ts";

// prettier-ignore
export const LAYOUT_GU_INSCRIPT: CharacterDict = {
  Digit1: [/* DIGIT ONE */ 0x0031, /* GUJARATI VOWEL CANDRA E */ 0x0a8d, /* GUJARATI DIGIT ONE */ 0x0ae7],
  Digit2: [/* DIGIT TWO */ 0x0032, /* GUJARATI VOWEL SIGN CANDRA E */ 0x0ac5, /* GUJARATI DIGIT TWO */ 0x0ae8],
  Digit3: [/* DIGIT THREE */ 0x0033, { ligature: "્ર" }, /* GUJARATI DIGIT THREE */ 0x0ae9],
  Digit4: [/* DIGIT FOUR */ 0x0034, { ligature: "ર્" }, /* GUJARATI DIGIT FOUR */ 0x0aea],
  Digit5: [/* DIGIT FIVE */ 0x0035, { ligature: "જ્ઞ" }, /* GUJARATI DIGIT FIVE */ 0x0aeb],
  Digit6: [/* DIGIT SIX */ 0x0036, { ligature: "ત્ર" }, /* GUJARATI DIGIT SIX */ 0x0aec],
  Digit7: [/* DIGIT SEVEN */ 0x0037, { ligature: "ક્ષ" }, /* GUJARATI DIGIT SEVEN */ 0x0aed],
  Digit8: [/* DIGIT EIGHT */ 0x0038, { ligature: "શ્ર" }, /* GUJARATI DIGIT EIGHT */ 0x0aee],
  Digit9: [/* DIGIT NINE */ 0x0039, /* LEFT PARENTHESIS */ 0x0028, /* GUJARATI DIGIT NINE */ 0x0aef],
  Digit0: [/* DIGIT ZERO */ 0x0030, /* RIGHT PARENTHESIS */ 0x0029, /* GUJARATI DIGIT ZERO */ 0x0ae6],
  Minus: [/* HYPHEN-MINUS */ 0x002d, /* GUJARATI SIGN VISARGA */ 0x0a83],
  Equal: [/* GUJARATI VOWEL SIGN VOCALIC R */ 0x0ac3, /* GUJARATI LETTER VOCALIC R */ 0x0a8b, /* GUJARATI VOWEL SIGN VOCALIC RR */ 0x0ac4, /* GUJARATI LETTER VOCALIC RR */ 0x0ae0],
  KeyQ: [/* GUJARATI VOWEL SIGN AU */ 0x0acc, /* GUJARATI LETTER AU */ 0x0a94],
  KeyW: [/* GUJARATI VOWEL SIGN AI */ 0x0ac8, /* GUJARATI LETTER AI */ 0x0a90],
  KeyE: [/* GUJARATI VOWEL SIGN AA */ 0x0abe, /* GUJARATI LETTER AA */ 0x0a86],
  KeyR: [/* GUJARATI VOWEL SIGN II */ 0x0ac0, /* GUJARATI LETTER II */ 0x0a88],
  KeyT: [/* GUJARATI VOWEL SIGN UU */ 0x0ac2, /* GUJARATI LETTER UU */ 0x0a8a],
  KeyY: [/* GUJARATI LETTER BA */ 0x0aac, /* GUJARATI LETTER BHA */ 0x0aad],
  KeyU: [/* GUJARATI LETTER HA */ 0x0ab9, /* GUJARATI LETTER NGA */ 0x0a99],
  KeyI: [/* GUJARATI LETTER GA */ 0x0a97, /* GUJARATI LETTER GHA */ 0x0a98],
  KeyO: [/* GUJARATI LETTER DA */ 0x0aa6, /* GUJARATI LETTER DHA */ 0x0aa7],
  KeyP: [/* GUJARATI LETTER JA */ 0x0a9c, /* GUJARATI LETTER JHA */ 0x0a9d],
  BracketLeft: [/* GUJARATI LETTER DDA */ 0x0aa1, /* GUJARATI LETTER DDHA */ 0x0aa2],
  BracketRight: [/* GUJARATI SIGN NUKTA */ 0x0abc, /* GUJARATI LETTER NYA */ 0x0a9e],
  Backslash: [/* GUJARATI VOWEL SIGN CANDRA O */ 0x0ac9, /* GUJARATI VOWEL CANDRA O */ 0x0a91],
  KeyA: [/* GUJARATI VOWEL SIGN O */ 0x0acb, /* GUJARATI LETTER O */ 0x0a93],
  KeyS: [/* GUJARATI VOWEL SIGN E */ 0x0ac7, /* GUJARATI LETTER E */ 0x0a8f],
  KeyD: [/* GUJARATI SIGN VIRAMA */ 0x0acd, /* GUJARATI LETTER A */ 0x0a85],
  KeyF: [/* GUJARATI VOWEL SIGN I */ 0x0abf, /* GUJARATI LETTER I */ 0x0a87],
  KeyG: [/* GUJARATI VOWEL SIGN U */ 0x0ac1, /* GUJARATI LETTER U */ 0x0a89],
  KeyH: [/* GUJARATI LETTER PA */ 0x0aaa, /* GUJARATI LETTER PHA */ 0x0aab],
  KeyJ: [/* GUJARATI LETTER RA */ 0x0ab0],
  KeyK: [/* GUJARATI LETTER KA */ 0x0a95, /* GUJARATI LETTER KHA */ 0x0a96],
  KeyL: [/* GUJARATI LETTER TA */ 0x0aa4, /* GUJARATI LETTER THA */ 0x0aa5],
  Semicolon: [/* GUJARATI LETTER CA */ 0x0a9a, /* GUJARATI LETTER CHA */ 0x0a9b],
  Quote: [/* GUJARATI LETTER TTA */ 0x0a9f, /* GUJARATI LETTER TTHA */ 0x0aa0],
  KeyX: [/* GUJARATI SIGN ANUSVARA */ 0x0a82, /* GUJARATI SIGN CANDRABINDU */ 0x0a81, null, /* GUJARATI OM */ 0x0ad0],
  KeyC: [/* GUJARATI LETTER MA */ 0x0aae, /* GUJARATI LETTER NNA */ 0x0aa3],
  KeyV: [/* GUJARATI LETTER NA */ 0x0aa8],
  KeyB: [/* GUJARATI LETTER VA */ 0x0ab5],
  KeyN: [/* GUJARATI LETTER LA */ 0x0ab2, /* GUJARATI LETTER LLA */ 0x0ab3],
  KeyM: [/* GUJARATI LETTER SA */ 0x0ab8, /* GUJARATI LETTER SHA */ 0x0ab6],
  Comma: [/* COMMA */ 0x002c, /* GUJARATI LETTER SSA */ 0x0ab7],
  Period: [/* FULL STOP */ 0x002e, /* DEVANAGARI DANDA */ 0x0964, /* DEVANAGARI DOUBLE DANDA */ 0x0965, /* GUJARATI SIGN AVAGRAHA */ 0x0abd],
  Slash: [/* GUJARATI LETTER YA */ 0x0aaf],
  Space: [/* SPACE */ 0x0020],
};
