// Generated file, do not edit.

import { type CharacterDict } from "../types.ts";

// prettier-ignore
export const LAYOUT_KN_PHONETIC: CharacterDict = {
  Backquote: [/* KANNADA VOWEL SIGN E */ 0x0cc6, /* KANNADA LETTER E */ 0x0c8e],
  Digit1: [/* KANNADA DIGIT ONE */ 0x0ce7, /* EXCLAMATION MARK */ 0x0021],
  Digit2: [/* KANNADA DIGIT TWO */ 0x0ce8, /* COMMERCIAL AT */ 0x0040],
  Digit3: [/* KANNADA DIGIT THREE */ 0x0ce9, /* NUMBER SIGN */ 0x0023],
  Digit4: [/* KANNADA DIGIT FOUR */ 0x0cea, /* DOLLAR SIGN */ 0x0024],
  Digit5: [/* KANNADA DIGIT FIVE */ 0x0ceb, /* PERCENT SIGN */ 0x0025],
  Digit6: [/* KANNADA DIGIT SIX */ 0x0cec, /* CIRCUMFLEX ACCENT */ 0x005e],
  Digit7: [/* KANNADA DIGIT SEVEN */ 0x0ced, /* AMPERSAND */ 0x0026],
  Digit8: [/* KANNADA DIGIT EIGHT */ 0x0cee, /* ASTERISK */ 0x002a],
  Digit9: [/* KANNADA DIGIT NINE */ 0x0cef, /* LEFT PARENTHESIS */ 0x0028],
  Digit0: [/* KANNADA DIGIT ZERO */ 0x0ce6, /* RIGHT PARENTHESIS */ 0x0029],
  Minus: [/* HYPHEN-MINUS */ 0x002d, /* LOW LINE */ 0x005f],
  Equal: [/* EQUALS SIGN */ 0x003d, /* PLUS SIGN */ 0x002b],
  KeyW: [/* KANNADA LETTER A */ 0x0c85, /* KANNADA LETTER AA */ 0x0c86],
  KeyE: [/* KANNADA VOWEL SIGN EE */ 0x0cc7, /* KANNADA VOWEL SIGN AI */ 0x0cc8],
  KeyR: [/* KANNADA LETTER RA */ 0x0cb0, /* KANNADA VOWEL SIGN VOCALIC R */ 0x0cc3],
  KeyT: [/* KANNADA LETTER TA */ 0x0ca4, /* KANNADA LETTER THA */ 0x0ca5],
  KeyY: [/* KANNADA LETTER YA */ 0x0caf],
  KeyU: [/* KANNADA VOWEL SIGN U */ 0x0cc1, /* KANNADA VOWEL SIGN UU */ 0x0cc2],
  KeyI: [/* KANNADA VOWEL SIGN I */ 0x0cbf, /* KANNADA VOWEL SIGN II */ 0x0cc0],
  KeyO: [/* KANNADA VOWEL SIGN OO */ 0x0ccb, /* KANNADA VOWEL SIGN AU */ 0x0ccc],
  KeyP: [/* KANNADA LETTER PA */ 0x0caa, /* KANNADA LETTER PHA */ 0x0cab],
  BracketLeft: [null, /* LEFT SQUARE BRACKET */ 0x005b],
  BracketRight: [/* KANNADA LETTER RA */ 0x0cb0, /* RIGHT SQUARE BRACKET */ 0x005d],
  Backslash: [/* KANNADA VOWEL SIGN O */ 0x0cca, /* KANNADA LETTER O */ 0x0c92],
  KeyA: [/* KANNADA VOWEL SIGN AA */ 0x0cbe, /* KANNADA VOWEL SIGN AA */ 0x0cbe],
  KeyS: [/* KANNADA LETTER SA */ 0x0cb8, /* KANNADA LETTER SHA */ 0x0cb6],
  KeyD: [/* KANNADA LETTER DA */ 0x0ca6, /* KANNADA LETTER DHA */ 0x0ca7],
  KeyF: [/* KANNADA SIGN VIRAMA */ 0x0ccd],
  KeyG: [/* KANNADA LETTER GA */ 0x0c97, /* KANNADA LETTER GHA */ 0x0c98],
  KeyH: [/* KANNADA LETTER HA */ 0x0cb9, /* KANNADA SIGN VISARGA */ 0x0c83],
  KeyJ: [/* KANNADA LETTER JA */ 0x0c9c, /* KANNADA LETTER JHA */ 0x0c9d],
  KeyK: [/* KANNADA LETTER KA */ 0x0c95, /* KANNADA LETTER KHA */ 0x0c96],
  KeyL: [/* KANNADA LETTER LA */ 0x0cb2, /* KANNADA LETTER LLA */ 0x0cb3],
  Semicolon: [/* SEMICOLON */ 0x003b, /* COLON */ 0x003a],
  Quote: [/* APOSTROPHE */ 0x0027, /* QUOTATION MARK */ 0x0022],
  KeyZ: [/* KANNADA LETTER NGA */ 0x0c99],
  KeyX: [/* KANNADA LETTER SSA */ 0x0cb7, { ligature: "ಕ್ಷ" }],
  KeyC: [/* KANNADA LETTER CA */ 0x0c9a, /* KANNADA LETTER CHA */ 0x0c9b],
  KeyV: [/* KANNADA LETTER VA */ 0x0cb5],
  KeyB: [/* KANNADA LETTER BA */ 0x0cac, /* KANNADA LETTER BHA */ 0x0cad],
  KeyN: [/* KANNADA LETTER NA */ 0x0ca8, /* KANNADA LETTER NNA */ 0x0ca3],
  KeyM: [/* KANNADA LETTER MA */ 0x0cae, /* KANNADA SIGN ANUSVARA */ 0x0c82],
  Comma: [/* COMMA */ 0x002c, /* LESS-THAN SIGN */ 0x003c],
  Period: [null, /* GREATER-THAN SIGN */ 0x003e],
  Slash: [/* SOLIDUS */ 0x002f, /* QUESTION MARK */ 0x003f],
  Space: [/* SPACE */ 0x0020],
};
