// Generated file, do not edit.

import { type CharacterDict } from "../types.ts";

// prettier-ignore
export const LAYOUT_BN_INSCRIPT: CharacterDict = {
  Backquote: [/* DEVANAGARI DOUBLE DANDA */ 0x0965, { ligature: "অ্যা" }],
  Digit1: [/* BENGALI DIGIT ONE */ 0x09e7, /* EXCLAMATION MARK */ 0x0021],
  Digit2: [/* BENGALI DIGIT TWO */ 0x09e8, /* COMMERCIAL AT */ 0x0040],
  Digit3: [/* BENGALI DIGIT THREE */ 0x09e9, { ligature: "্র" }],
  Digit4: [/* BENGALI DIGIT FOUR */ 0x09ea, { ligature: "র্" }],
  Digit5: [/* BENGALI DIGIT FIVE */ 0x09eb, { ligature: "জ্ঞ" }],
  Digit6: [/* BENGALI DIGIT SIX */ 0x09ec, { ligature: "ত্র" }],
  Digit7: [/* BENGALI DIGIT SEVEN */ 0x09ed, { ligature: "ক্ষ" }],
  Digit8: [/* BENGALI DIGIT EIGHT */ 0x09ee, { ligature: "শ্র" }],
  Digit9: [/* BENGALI DIGIT NINE */ 0x09ef, /* LEFT PARENTHESIS */ 0x0028],
  Digit0: [/* BENGALI DIGIT ZERO */ 0x09e6, /* RIGHT PARENTHESIS */ 0x0029],
  Minus: [/* HYPHEN-MINUS */ 0x002d, /* BENGALI SIGN VISARGA */ 0x0983],
  Equal: [/* BENGALI VOWEL SIGN VOCALIC R */ 0x09c3, /* BENGALI LETTER VOCALIC R */ 0x098b],
  KeyQ: [/* BENGALI VOWEL SIGN AU */ 0x09cc, /* BENGALI LETTER AU */ 0x0994],
  KeyW: [/* BENGALI VOWEL SIGN AI */ 0x09c8, /* BENGALI LETTER AI */ 0x0990],
  KeyE: [/* BENGALI VOWEL SIGN AA */ 0x09be, /* BENGALI LETTER AA */ 0x0986],
  KeyR: [/* BENGALI VOWEL SIGN II */ 0x09c0, /* BENGALI LETTER II */ 0x0988],
  KeyT: [/* BENGALI VOWEL SIGN UU */ 0x09c2, /* BENGALI LETTER UU */ 0x098a],
  KeyY: [/* BENGALI LETTER BA */ 0x09ac, /* BENGALI LETTER BHA */ 0x09ad],
  KeyU: [/* BENGALI LETTER HA */ 0x09b9, /* BENGALI LETTER NGA */ 0x0999],
  KeyI: [/* BENGALI LETTER GA */ 0x0997, /* BENGALI LETTER GHA */ 0x0998],
  KeyO: [/* BENGALI LETTER DA */ 0x09a6, /* BENGALI LETTER DHA */ 0x09a7],
  KeyP: [/* BENGALI LETTER JA */ 0x099c, /* BENGALI LETTER JHA */ 0x099d],
  BracketLeft: [/* BENGALI LETTER DDA */ 0x09a1, /* BENGALI LETTER DDHA */ 0x09a2],
  BracketRight: [/* BENGALI SIGN NUKTA */ 0x09bc, /* BENGALI LETTER NYA */ 0x099e],
  KeyA: [/* BENGALI VOWEL SIGN O */ 0x09cb, /* BENGALI LETTER O */ 0x0993],
  KeyS: [/* BENGALI VOWEL SIGN E */ 0x09c7, /* BENGALI LETTER E */ 0x098f],
  KeyD: [/* BENGALI SIGN VIRAMA */ 0x09cd, /* BENGALI LETTER A */ 0x0985],
  KeyF: [/* BENGALI VOWEL SIGN I */ 0x09bf, /* BENGALI LETTER I */ 0x0987],
  KeyG: [/* BENGALI VOWEL SIGN U */ 0x09c1, /* BENGALI LETTER U */ 0x0989],
  KeyH: [/* BENGALI LETTER PA */ 0x09aa, /* BENGALI LETTER PHA */ 0x09ab],
  KeyJ: [/* BENGALI LETTER RA */ 0x09b0, /* BENGALI LETTER KHANDA TA */ 0x09ce],
  KeyK: [/* BENGALI LETTER KA */ 0x0995, /* BENGALI LETTER KHA */ 0x0996],
  KeyL: [/* BENGALI LETTER TA */ 0x09a4, /* BENGALI LETTER THA */ 0x09a5],
  Semicolon: [/* BENGALI LETTER CA */ 0x099a, /* BENGALI LETTER CHA */ 0x099b],
  Quote: [/* BENGALI LETTER TTA */ 0x099f, /* BENGALI LETTER TTHA */ 0x09a0],
  KeyX: [/* BENGALI SIGN ANUSVARA */ 0x0982, /* BENGALI SIGN CANDRABINDU */ 0x0981],
  KeyC: [/* BENGALI LETTER MA */ 0x09ae, /* BENGALI LETTER NNA */ 0x09a3],
  KeyV: [/* BENGALI LETTER NA */ 0x09a8],
  KeyB: [/* BENGALI LETTER BA */ 0x09ac],
  KeyN: [/* BENGALI LETTER LA */ 0x09b2],
  KeyM: [/* BENGALI LETTER SA */ 0x09b8, /* BENGALI LETTER SHA */ 0x09b6],
  Comma: [/* COMMA */ 0x002c, /* BENGALI LETTER SSA */ 0x09b7],
  Period: [/* FULL STOP */ 0x002e, /* DEVANAGARI DANDA */ 0x0964],
  Slash: [/* BENGALI LETTER YYA */ 0x09df, /* BENGALI LETTER YA */ 0x09af],
  Space: [/* SPACE */ 0x0020],
};
