// Generated file, do not edit.

import { type CharacterDict } from "../types.ts";

// prettier-ignore
export const LAYOUT_GU_PHONETIC: CharacterDict = {
  Digit1: [/* GUJARATI DIGIT ONE */ 0x0ae7, /* EXCLAMATION MARK */ 0x0021],
  Digit2: [/* GUJARATI DIGIT TWO */ 0x0ae8, /* COMMERCIAL AT */ 0x0040],
  Digit3: [/* GUJARATI DIGIT THREE */ 0x0ae9, /* NUMBER SIGN */ 0x0023],
  Digit4: [/* GUJARATI DIGIT FOUR */ 0x0aea, /* DOLLAR SIGN */ 0x0024],
  Digit5: [/* GUJARATI DIGIT FIVE */ 0x0aeb, /* PERCENT SIGN */ 0x0025],
  Digit6: [/* GUJARATI DIGIT SIX */ 0x0aec, /* CIRCUMFLEX ACCENT */ 0x005e],
  Digit7: [/* GUJARATI DIGIT SEVEN */ 0x0aed, /* AMPERSAND */ 0x0026],
  Digit8: [/* GUJARATI DIGIT EIGHT */ 0x0aee, /* ASTERISK */ 0x002a],
  Digit9: [/* GUJARATI DIGIT NINE */ 0x0aef, /* LEFT PARENTHESIS */ 0x0028],
  Digit0: [/* GUJARATI DIGIT ZERO */ 0x0ae6, /* RIGHT PARENTHESIS */ 0x0029],
  Minus: [/* HYPHEN-MINUS */ 0x002d, /* LOW LINE */ 0x005f],
  Equal: [/* EQUALS SIGN */ 0x003d, /* PLUS SIGN */ 0x002b],
  KeyQ: [/* GUJARATI VOWEL SIGN CANDRA E */ 0x0ac5, /* GUJARATI VOWEL SIGN CANDRA O */ 0x0ac9],
  KeyW: [/* GUJARATI LETTER A */ 0x0a85, /* GUJARATI LETTER AA */ 0x0a86],
  KeyE: [/* GUJARATI VOWEL SIGN E */ 0x0ac7, /* GUJARATI VOWEL SIGN AI */ 0x0ac8],
  KeyR: [/* GUJARATI LETTER RA */ 0x0ab0, /* GUJARATI VOWEL SIGN VOCALIC R */ 0x0ac3],
  KeyT: [/* GUJARATI LETTER TA */ 0x0aa4, /* GUJARATI LETTER THA */ 0x0aa5],
  KeyY: [/* GUJARATI LETTER YA */ 0x0aaf],
  KeyU: [/* GUJARATI VOWEL SIGN U */ 0x0ac1, /* GUJARATI VOWEL SIGN UU */ 0x0ac2],
  KeyI: [/* GUJARATI VOWEL SIGN I */ 0x0abf, /* GUJARATI VOWEL SIGN II */ 0x0ac0],
  KeyO: [/* GUJARATI VOWEL SIGN O */ 0x0acb, /* GUJARATI VOWEL SIGN AU */ 0x0acc],
  KeyP: [/* GUJARATI LETTER PA */ 0x0aaa, /* GUJARATI LETTER PHA */ 0x0aab],
  BracketLeft: [null, /* LEFT SQUARE BRACKET */ 0x005b],
  BracketRight: [null, /* RIGHT SQUARE BRACKET */ 0x005d],
  KeyA: [/* GUJARATI VOWEL SIGN AA */ 0x0abe, /* GUJARATI VOWEL SIGN AA */ 0x0abe],
  KeyS: [/* GUJARATI LETTER SA */ 0x0ab8, /* GUJARATI LETTER SHA */ 0x0ab6],
  KeyD: [/* GUJARATI LETTER DA */ 0x0aa6, /* GUJARATI LETTER DHA */ 0x0aa7],
  KeyF: [/* GUJARATI SIGN VIRAMA */ 0x0acd, /* GUJARATI SIGN NUKTA */ 0x0abc],
  KeyG: [/* GUJARATI LETTER GA */ 0x0a97, /* GUJARATI LETTER GHA */ 0x0a98],
  KeyH: [/* GUJARATI LETTER HA */ 0x0ab9, /* GUJARATI SIGN VISARGA */ 0x0a83],
  KeyJ: [/* GUJARATI LETTER JA */ 0x0a9c, /* GUJARATI LETTER JHA */ 0x0a9d],
  KeyK: [/* GUJARATI LETTER KA */ 0x0a95, /* GUJARATI LETTER KHA */ 0x0a96],
  KeyL: [/* GUJARATI LETTER LA */ 0x0ab2, /* GUJARATI LETTER LLA */ 0x0ab3],
  Semicolon: [/* SEMICOLON */ 0x003b, /* COLON */ 0x003a],
  Quote: [/* APOSTROPHE */ 0x0027, /* QUOTATION MARK */ 0x0022],
  KeyZ: [/* GUJARATI LETTER NGA */ 0x0a99, /* GUJARATI SIGN CANDRABINDU */ 0x0a81],
  KeyX: [/* GUJARATI LETTER SSA */ 0x0ab7, { ligature: "ક્ષ" }],
  KeyC: [/* GUJARATI LETTER CA */ 0x0a9a, /* GUJARATI LETTER CHA */ 0x0a9b],
  KeyV: [/* GUJARATI LETTER VA */ 0x0ab5],
  KeyB: [/* GUJARATI LETTER BA */ 0x0aac, /* GUJARATI LETTER BHA */ 0x0aad],
  KeyN: [/* GUJARATI LETTER NA */ 0x0aa8, /* GUJARATI LETTER NNA */ 0x0aa3],
  KeyM: [/* GUJARATI LETTER MA */ 0x0aae, /* GUJARATI SIGN ANUSVARA */ 0x0a82],
  Comma: [/* COMMA */ 0x002c, /* LESS-THAN SIGN */ 0x003c],
  Period: [/* FULL STOP */ 0x002e, /* GREATER-THAN SIGN */ 0x003e],
  Slash: [/* SOLIDUS */ 0x002f, /* QUESTION MARK */ 0x003f],
  Space: [/* SPACE */ 0x0020],
};
