// Generated file, do not edit.

import { type CharacterDict } from "../types.ts";

// prettier-ignore
export const LAYOUT_KN_INSCRIPT: CharacterDict = {
  Backquote: [/* KANNADA VOWEL SIGN O */ 0x0cca, /* KANNADA LETTER O */ 0x0c92],
  Digit1: [/* DIGIT ONE */ 0x0031, null, /* KANNADA DIGIT ONE */ 0x0ce7],
  Digit2: [/* DIGIT TWO */ 0x0032, null, /* KANNADA DIGIT TWO */ 0x0ce8],
  Digit3: [/* DIGIT THREE */ 0x0033, { ligature: "್ರ" }, /* KANNADA DIGIT THREE */ 0x0ce9],
  Digit4: [/* DIGIT FOUR */ 0x0034, { ligature: "ರ್" }, /* KANNADA DIGIT FOUR */ 0x0cea],
  Digit5: [/* DIGIT FIVE */ 0x0035, { ligature: "ಜ್ಞ" }, /* KANNADA DIGIT FIVE */ 0x0ceb],
  Digit6: [/* DIGIT SIX */ 0x0036, { ligature: "ತ್ರ" }, /* KANNADA DIGIT SIX */ 0x0cec],
  Digit7: [/* DIGIT SEVEN */ 0x0037, { ligature: "ಕ್ಷ" }, /* KANNADA DIGIT SEVEN */ 0x0ced],
  Digit8: [/* DIGIT EIGHT */ 0x0038, { ligature: "ಶ್ರ" }, /* KANNADA DIGIT EIGHT */ 0x0cee],
  Digit9: [/* DIGIT NINE */ 0x0039, /* LEFT PARENTHESIS */ 0x0028, /* KANNADA DIGIT NINE */ 0x0cef],
  Digit0: [/* DIGIT ZERO */ 0x0030, /* RIGHT PARENTHESIS */ 0x0029, /* KANNADA DIGIT ZERO */ 0x0ce6],
  Minus: [/* HYPHEN-MINUS */ 0x002d, /* KANNADA SIGN VISARGA */ 0x0c83],
  Equal: [/* KANNADA VOWEL SIGN VOCALIC R */ 0x0cc3, /* KANNADA LETTER VOCALIC R */ 0x0c8b, /* KANNADA VOWEL SIGN VOCALIC RR */ 0x0cc4, /* KANNADA LETTER VOCALIC RR */ 0x0ce0],
  KeyQ: [/* KANNADA VOWEL SIGN AU */ 0x0ccc, /* KANNADA LETTER AU */ 0x0c94],
  KeyW: [/* KANNADA VOWEL SIGN AI */ 0x0cc8, /* KANNADA LETTER AI */ 0x0c90, /* KANNADA AI LENGTH MARK */ 0x0cd6],
  KeyE: [/* KANNADA VOWEL SIGN AA */ 0x0cbe, /* KANNADA LETTER AA */ 0x0c86],
  KeyR: [/* KANNADA VOWEL SIGN II */ 0x0cc0, /* KANNADA LETTER II */ 0x0c88, null, /* KANNADA LETTER VOCALIC LL */ 0x0ce1],
  KeyT: [/* KANNADA VOWEL SIGN UU */ 0x0cc2, /* KANNADA LETTER UU */ 0x0c8a],
  KeyY: [/* KANNADA LETTER BA */ 0x0cac, /* KANNADA LETTER BHA */ 0x0cad],
  KeyU: [/* KANNADA LETTER HA */ 0x0cb9, /* KANNADA LETTER NGA */ 0x0c99],
  KeyI: [/* KANNADA LETTER GA */ 0x0c97, /* KANNADA LETTER GHA */ 0x0c98],
  KeyO: [/* KANNADA LETTER DA */ 0x0ca6, /* KANNADA LETTER DHA */ 0x0ca7],
  KeyP: [/* KANNADA LETTER JA */ 0x0c9c, /* KANNADA LETTER JHA */ 0x0c9d],
  BracketLeft: [/* KANNADA LETTER DDA */ 0x0ca1, /* KANNADA LETTER DDHA */ 0x0ca2],
  BracketRight: [null, /* KANNADA LETTER NYA */ 0x0c9e],
  KeyA: [/* KANNADA VOWEL SIGN OO */ 0x0ccb, /* KANNADA LETTER OO */ 0x0c93],
  KeyS: [/* KANNADA VOWEL SIGN EE */ 0x0cc7, /* KANNADA LETTER EE */ 0x0c8f, /* KANNADA LENGTH MARK */ 0x0cd5],
  KeyD: [/* KANNADA SIGN VIRAMA */ 0x0ccd, /* KANNADA LETTER A */ 0x0c85],
  KeyF: [/* KANNADA VOWEL SIGN I */ 0x0cbf, /* KANNADA LETTER I */ 0x0c87, null, /* KANNADA LETTER VOCALIC L */ 0x0c8c],
  KeyG: [/* KANNADA VOWEL SIGN U */ 0x0cc1, /* KANNADA LETTER U */ 0x0c89],
  KeyH: [/* KANNADA LETTER PA */ 0x0caa, /* KANNADA LETTER PHA */ 0x0cab, null, /* KANNADA LETTER FA */ 0x0cde],
  KeyJ: [/* KANNADA LETTER RA */ 0x0cb0, /* KANNADA LETTER RRA */ 0x0cb1],
  KeyK: [/* KANNADA LETTER KA */ 0x0c95, /* KANNADA LETTER KHA */ 0x0c96],
  KeyL: [/* KANNADA LETTER TA */ 0x0ca4, /* KANNADA LETTER THA */ 0x0ca5],
  Semicolon: [/* KANNADA LETTER CA */ 0x0c9a, /* KANNADA LETTER CHA */ 0x0c9b],
  Quote: [/* KANNADA LETTER TTA */ 0x0c9f, /* KANNADA LETTER TTHA */ 0x0ca0],
  KeyZ: [/* KANNADA VOWEL SIGN E */ 0x0cc6, /* KANNADA LETTER E */ 0x0c8e],
  KeyX: [/* KANNADA SIGN ANUSVARA */ 0x0c82],
  KeyC: [/* KANNADA LETTER MA */ 0x0cae, /* KANNADA LETTER NNA */ 0x0ca3],
  KeyV: [/* KANNADA LETTER NA */ 0x0ca8],
  KeyB: [/* KANNADA LETTER VA */ 0x0cb5],
  KeyN: [/* KANNADA LETTER LA */ 0x0cb2, /* KANNADA LETTER LLA */ 0x0cb3],
  KeyM: [/* KANNADA LETTER SA */ 0x0cb8, /* KANNADA LETTER SHA */ 0x0cb6],
  Comma: [/* COMMA */ 0x002c, /* KANNADA LETTER SSA */ 0x0cb7],
  Period: [/* FULL STOP */ 0x002e, /* VERTICAL LINE */ 0x007c],
  Slash: [/* KANNADA LETTER YA */ 0x0caf],
  Space: [/* SPACE */ 0x0020],
};
