// Generated file, do not edit.

import { type CharacterDict } from "../types.ts";

// prettier-ignore
export const LAYOUT_TA_INSCRIPT: CharacterDict = {
  Backquote: [/* TAMIL VOWEL SIGN O */ 0x0bca, /* TAMIL LETTER O */ 0x0b92],
  Digit1: [/* DIGIT ONE */ 0x0031, null, /* TAMIL DIGIT ONE */ 0x0be7],
  Digit2: [/* DIGIT TWO */ 0x0032, null, /* TAMIL DIGIT TWO */ 0x0be8],
  Digit3: [/* DIGIT THREE */ 0x0033, null, /* TAMIL DIGIT THREE */ 0x0be9],
  Digit4: [/* DIGIT FOUR */ 0x0034, null, /* TAMIL DIGIT FOUR */ 0x0bea],
  Digit5: [/* DIGIT FIVE */ 0x0035, null, /* TAMIL DIGIT FIVE */ 0x0beb],
  Digit6: [/* DIGIT SIX */ 0x0036, { ligature: "த்ர" }, /* TAMIL DIGIT SIX */ 0x0bec],
  Digit7: [/* DIGIT SEVEN */ 0x0037, { ligature: "க்ஷ" }, /* TAMIL DIGIT SEVEN */ 0x0bed],
  Digit8: [/* DIGIT EIGHT */ 0x0038, { ligature: "ஷ்ர" }, /* TAMIL DIGIT EIGHT */ 0x0bee],
  Digit9: [/* DIGIT NINE */ 0x0039, null, /* TAMIL DIGIT NINE */ 0x0bef],
  Digit0: [/* DIGIT ZERO */ 0x0030, /* TAMIL NUMBER TEN */ 0x0bf0, /* TAMIL DIGIT ZERO */ 0x0be6],
  Minus: [/* HYPHEN-MINUS */ 0x002d, /* TAMIL SIGN VISARGA */ 0x0b83, /* TAMIL NUMBER ONE HUNDRED */ 0x0bf1],
  Equal: [null, null, /* TAMIL NUMBER ONE THOUSAND */ 0x0bf2],
  KeyQ: [/* TAMIL VOWEL SIGN AU */ 0x0bcc, /* TAMIL LETTER AU */ 0x0b94],
  KeyW: [/* TAMIL VOWEL SIGN AI */ 0x0bc8, /* TAMIL LETTER AI */ 0x0b90],
  KeyE: [/* TAMIL VOWEL SIGN AA */ 0x0bbe, /* TAMIL LETTER AA */ 0x0b86],
  KeyR: [/* TAMIL VOWEL SIGN II */ 0x0bc0, /* TAMIL LETTER II */ 0x0b88],
  KeyT: [/* TAMIL VOWEL SIGN UU */ 0x0bc2, /* TAMIL LETTER UU */ 0x0b8a],
  KeyY: [/* TAMIL LETTER PA */ 0x0baa, /* TAMIL LETTER PA */ 0x0baa, /* TAMIL CREDIT SIGN */ 0x0bf7],
  KeyU: [/* TAMIL LETTER HA */ 0x0bb9, /* TAMIL LETTER NGA */ 0x0b99],
  KeyI: [/* TAMIL LETTER KA */ 0x0b95, /* TAMIL LETTER KA */ 0x0b95],
  KeyO: [/* TAMIL LETTER TA */ 0x0ba4, /* TAMIL LETTER TA */ 0x0ba4],
  KeyP: [/* TAMIL LETTER JA */ 0x0b9c, /* TAMIL LETTER CA */ 0x0b9a],
  BracketLeft: [/* TAMIL LETTER TTA */ 0x0b9f, /* TAMIL LETTER TTA */ 0x0b9f],
  BracketRight: [/* TAMIL LETTER NYA */ 0x0b9e, /* TAMIL LETTER NYA */ 0x0b9e],
  KeyA: [/* TAMIL VOWEL SIGN OO */ 0x0bcb, /* TAMIL LETTER OO */ 0x0b93],
  KeyS: [/* TAMIL VOWEL SIGN EE */ 0x0bc7, /* TAMIL LETTER EE */ 0x0b8f],
  KeyD: [/* TAMIL SIGN VIRAMA */ 0x0bcd, /* TAMIL LETTER A */ 0x0b85],
  KeyF: [/* TAMIL VOWEL SIGN I */ 0x0bbf, /* TAMIL LETTER I */ 0x0b87],
  KeyG: [/* TAMIL VOWEL SIGN U */ 0x0bc1, /* TAMIL LETTER U */ 0x0b89],
  KeyH: [/* TAMIL LETTER PA */ 0x0baa, /* TAMIL LETTER PA */ 0x0baa, /* TAMIL DEBIT SIGN */ 0x0bf6],
  KeyJ: [/* TAMIL LETTER RA */ 0x0bb0, /* TAMIL LETTER RRA */ 0x0bb1],
  KeyK: [/* TAMIL LETTER KA */ 0x0b95, /* TAMIL LETTER KA */ 0x0b95],
  KeyL: [/* TAMIL LETTER TA */ 0x0ba4, /* TAMIL LETTER TA */ 0x0ba4],
  Semicolon: [/* TAMIL LETTER CA */ 0x0b9a, /* TAMIL LETTER CA */ 0x0b9a],
  Quote: [/* TAMIL LETTER TTA */ 0x0b9f, /* TAMIL LETTER TTA */ 0x0b9f],
  KeyZ: [/* TAMIL VOWEL SIGN E */ 0x0bc6, /* TAMIL LETTER E */ 0x0b8e, /* TAMIL RUPEE SIGN */ 0x0bf9],
  KeyX: [null, /* TAMIL OM */ 0x0bd0, /* TAMIL NUMBER SIGN */ 0x0bfa],
  KeyC: [/* TAMIL LETTER MA */ 0x0bae, /* TAMIL LETTER NNA */ 0x0ba3, /* TAMIL MONTH SIGN */ 0x0bf4],
  KeyV: [/* TAMIL LETTER NA */ 0x0ba8, /* TAMIL LETTER NNNA */ 0x0ba9, /* TAMIL DAY SIGN */ 0x0bf3],
  KeyB: [/* TAMIL LETTER VA */ 0x0bb5, /* TAMIL LETTER LLLA */ 0x0bb4, /* TAMIL YEAR SIGN */ 0x0bf5],
  KeyN: [/* TAMIL LETTER LA */ 0x0bb2, /* TAMIL LETTER LLA */ 0x0bb3, /* TAMIL AS ABOVE SIGN */ 0x0bf8],
  KeyM: [/* TAMIL LETTER SA */ 0x0bb8, /* TAMIL LETTER SHA */ 0x0bb6],
  Comma: [/* COMMA */ 0x002c, /* TAMIL LETTER SSA */ 0x0bb7],
  Period: [/* FULL STOP */ 0x002e, { ligature: "ஸ்ரீ" }],
  Slash: [/* TAMIL LETTER YA */ 0x0baf, /* TAMIL LETTER YA */ 0x0baf],
  Space: [/* SPACE */ 0x0020],
};
