// Generated file, do not edit.

import { type CharacterDict } from "../types.ts";

// prettier-ignore
export const LAYOUT_TE_INSCRIPT: CharacterDict = {
  Backquote: [/* TELUGU VOWEL SIGN O */ 0x0c4a, /* TELUGU LETTER O */ 0x0c12],
  Digit1: [/* DIGIT ONE */ 0x0031, null, /* TELUGU DIGIT ONE */ 0x0c67],
  Digit2: [/* DIGIT TWO */ 0x0032, null, /* TELUGU DIGIT TWO */ 0x0c68],
  Digit3: [/* DIGIT THREE */ 0x0033, { ligature: "్ర" }, /* TELUGU DIGIT THREE */ 0x0c69],
  Digit4: [/* DIGIT FOUR */ 0x0034, null, /* TELUGU DIGIT FOUR */ 0x0c6a],
  Digit5: [/* DIGIT FIVE */ 0x0035, { ligature: "జ్ఞ" }, /* TELUGU DIGIT FIVE */ 0x0c6b],
  Digit6: [/* DIGIT SIX */ 0x0036, { ligature: "త్ర" }, /* TELUGU DIGIT SIX */ 0x0c6c],
  Digit7: [/* DIGIT SEVEN */ 0x0037, { ligature: "క్ష" }, /* TELUGU DIGIT SEVEN */ 0x0c6d],
  Digit8: [/* DIGIT EIGHT */ 0x0038, { ligature: "శ్ర" }, /* TELUGU DIGIT EIGHT */ 0x0c6e],
  Digit9: [/* DIGIT NINE */ 0x0039, /* LEFT PARENTHESIS */ 0x0028, /* TELUGU DIGIT NINE */ 0x0c6f],
  Digit0: [/* DIGIT ZERO */ 0x0030, /* RIGHT PARENTHESIS */ 0x0029, /* TELUGU DIGIT ZERO */ 0x0c66],
  Minus: [/* HYPHEN-MINUS */ 0x002d, /* TELUGU SIGN VISARGA */ 0x0c03],
  Equal: [/* TELUGU VOWEL SIGN VOCALIC R */ 0x0c43, /* TELUGU LETTER VOCALIC R */ 0x0c0b, /* TELUGU VOWEL SIGN VOCALIC RR */ 0x0c44, /* TELUGU LETTER VOCALIC RR */ 0x0c60],
  KeyQ: [/* TELUGU VOWEL SIGN AU */ 0x0c4c, /* TELUGU LETTER AU */ 0x0c14],
  KeyW: [/* TELUGU VOWEL SIGN AI */ 0x0c48, /* TELUGU LETTER AI */ 0x0c10, /* TELUGU AI LENGTH MARK */ 0x0c56],
  KeyE: [/* TELUGU VOWEL SIGN AA */ 0x0c3e, /* TELUGU LETTER AA */ 0x0c06],
  KeyR: [/* TELUGU VOWEL SIGN II */ 0x0c40, /* TELUGU LETTER II */ 0x0c08, null, /* TELUGU LETTER VOCALIC LL */ 0x0c61],
  KeyT: [/* TELUGU VOWEL SIGN UU */ 0x0c42, /* TELUGU LETTER UU */ 0x0c0a],
  KeyY: [/* TELUGU LETTER BA */ 0x0c2c, /* TELUGU LETTER BHA */ 0x0c2d],
  KeyU: [/* TELUGU LETTER HA */ 0x0c39, /* TELUGU LETTER NGA */ 0x0c19],
  KeyI: [/* TELUGU LETTER GA */ 0x0c17, /* TELUGU LETTER GHA */ 0x0c18],
  KeyO: [/* TELUGU LETTER DA */ 0x0c26, /* TELUGU LETTER DHA */ 0x0c27],
  KeyP: [/* TELUGU LETTER JA */ 0x0c1c, /* TELUGU LETTER JHA */ 0x0c1d, /* TELUGU LETTER DZA */ 0x0c59],
  BracketLeft: [/* TELUGU LETTER DDA */ 0x0c21, /* TELUGU LETTER DDHA */ 0x0c22],
  BracketRight: [null, /* TELUGU LETTER NYA */ 0x0c1e],
  KeyA: [/* TELUGU VOWEL SIGN OO */ 0x0c4b, /* TELUGU LETTER OO */ 0x0c13],
  KeyS: [/* TELUGU VOWEL SIGN EE */ 0x0c47, /* TELUGU LETTER EE */ 0x0c0f, /* TELUGU LENGTH MARK */ 0x0c55],
  KeyD: [/* TELUGU SIGN VIRAMA */ 0x0c4d, /* TELUGU LETTER A */ 0x0c05],
  KeyF: [/* TELUGU VOWEL SIGN I */ 0x0c3f, /* TELUGU LETTER I */ 0x0c07, null, /* TELUGU LETTER VOCALIC L */ 0x0c0c],
  KeyG: [/* TELUGU VOWEL SIGN U */ 0x0c41, /* TELUGU LETTER U */ 0x0c09],
  KeyH: [/* TELUGU LETTER PA */ 0x0c2a, /* TELUGU LETTER PHA */ 0x0c2b],
  KeyJ: [/* TELUGU LETTER RA */ 0x0c30, /* TELUGU LETTER RRA */ 0x0c31],
  KeyK: [/* TELUGU LETTER KA */ 0x0c15, /* TELUGU LETTER KHA */ 0x0c16],
  KeyL: [/* TELUGU LETTER TA */ 0x0c24, /* TELUGU LETTER THA */ 0x0c25],
  Semicolon: [/* TELUGU LETTER CA */ 0x0c1a, /* TELUGU LETTER CHA */ 0x0c1b, /* TELUGU LETTER TSA */ 0x0c58],
  Quote: [/* TELUGU LETTER TTA */ 0x0c1f, /* TELUGU LETTER TTHA */ 0x0c20],
  KeyZ: [/* TELUGU VOWEL SIGN E */ 0x0c46, /* TELUGU LETTER E */ 0x0c0e],
  KeyX: [/* TELUGU SIGN ANUSVARA */ 0x0c02, /* TELUGU SIGN CANDRABINDU */ 0x0c01],
  KeyC: [/* TELUGU LETTER MA */ 0x0c2e, /* TELUGU LETTER NNA */ 0x0c23],
  KeyV: [/* TELUGU LETTER NA */ 0x0c28, /* TELUGU LETTER NA */ 0x0c28],
  KeyB: [/* TELUGU LETTER VA */ 0x0c35],
  KeyN: [/* TELUGU LETTER LA */ 0x0c32, /* TELUGU LETTER LLA */ 0x0c33],
  KeyM: [/* TELUGU LETTER SA */ 0x0c38, /* TELUGU LETTER SHA */ 0x0c36],
  Comma: [/* COMMA */ 0x002c, /* TELUGU LETTER SSA */ 0x0c37],
  Period: [/* FULL STOP */ 0x002e],
  Slash: [/* TELUGU LETTER YA */ 0x0c2f],
  Space: [/* SPACE */ 0x0020],
};
