import { CacheControl } from "@fastr/headers";

const assetsCacheControl = new CacheControl({
  isPublic: true,
  noTransform: true, // Force Cloudflare to serve the compressed variants.
  maxAge: 31536000,
  ext: [["immutable", null]],
});

/**
 * The kids world's models, textures and sky maps: 11.5 MB on a cold load,
 * fetched by URLs with no content hash in them — so `immutable` would be a
 * lie, and a re-exported model would never reach a returning learner.
 *
 * With no header at all, which is what these had, a browser keeps the bytes
 * but must ask about every one of them on every visit: fifty conditional
 * requests answered 304, which on a slow link is seconds of round trips
 * before the first model can even be decoded. A day of freshness turns the
 * second visit into no requests at all, and bounds how long a changed model
 * can go unnoticed to that same day — after which the ETag revalidation
 * takes over, as before.
 */
const kidsAssetsCacheControl = new CacheControl({
  isPublic: true,
  noTransform: true,
  maxAge: 86400,
});

/** `/kids-assets/v1a2b3c4d/…` — see `unversion` in `static-cache.ts`. */
const VERSIONED = /^\/kids-assets\/v[0-9a-f]{8}\//;

export const cacheControl = (path: string): CacheControl | null => {
  if (process.env.NODE_ENV === "development") {
    // Do not cache assets when running Webpack in the watch mode.
    return new CacheControl({ isPrivate: true, noStore: true, maxAge: 0 });
  }
  if (path === "/sw.js") {
    /*
     * THE ONE SCRIPT THAT MUST NEVER BE CACHED.
     *
     * It is the thing that decides what everything else caches, so a stale
     * copy is the one failure with no way out from the outside: a browser
     * holding last month's worker would go on serving last month's rules
     * until it happened to check again.
     *
     * Browsers already revalidate a worker script on every update check and
     * cap any freshness at a day, so this is belt and braces — but it is the
     * cheap half of a very expensive mistake.
     */
    return new CacheControl({ isPrivate: true, noStore: true, maxAge: 0 });
  }
  if (path.startsWith("/assets/")) {
    // Assets generated by Webpack for the production env are immutable.
    return assetsCacheControl;
  }
  if (path.startsWith("/kids-assets/")) {
    // A VERSIONED URL CAN BE PROMISED FOREVER, because its hash IS its
    // bytes: re-export the model and every reference to it moves to a new
    // URL, so nothing cached under the old one can go stale. That is the
    // whole reason the segment exists — see `kids-manifest.mjs`.
    //
    // Un-versioned requests still happen and still get a day: a client whose
    // manifest failed to load falls back to the plain path, and it must get
    // a working game rather than an error.
    return VERSIONED.test(path) ? assetsCacheControl : kidsAssetsCacheControl;
  }
  return null;
};
