/**
 * THE NAMES OF THE ROAD THE LATER TIMES ROUND.
 *
 * Four chapters are authored (Lessons 1–40). A child who walks on is given
 * Chapter 5, 6, 7 … for ever, each built on one of those four roads again
 * (see `chapterNo` in chapters.ts). The numbers never repeat; this file makes
 * sure the NAMES do not either, for the first 500 lessons: every later
 * chapter has its own name and each of its ten lessons has its own.
 *
 * A LAP IS ONE MORE TIME ROUND ONE ROAD. `LAPS[road][i]` is that road's
 * (i + 2)th time through: Chapter 5 is the village's lap 1, Chapter 9 its
 * lap 2, and so on. Chapters up to 50 need twelve laps of the first two
 * roads and eleven of the other two — 46 chapters, 460 lessons.
 *
 * EVERY NAME FITS ITS SCENE. Lesson 6 of the fourth road is a wide
 * riverbank however many times a child walks it, so each of its names is a
 * riverbank; the village's seventh lesson is always a market. A name that
 * promised a pond or a hill the road does not have would be a small lie
 * told to a child who is looking straight at the road.
 *
 * PAST LESSON 500 the names come round again, still road by road — so a
 * reused name still lands on the scenery it was written for.
 *
 * The first two laps keep the chapter names repeats have always had, so
 * nobody past Lesson 40 finds their chapter renamed.
 */
export type Lap = {
  readonly name: string;
  /** Ten lesson names, in the order of the road's own ten lessons. */
  readonly lessons: readonly string[];
};

export const LAPS: Readonly<Record<number, readonly Lap[]>> = {
  // The Village: Edge, Farmland, Orchard, Homestead, Centre, Estate,
  // Market, Grazing Land, Pasture, Fern Meadow.
  1: [
    {
      name: "The Paddy Village",
      lessons: [
        "Paddy Gate",
        "Rice Fields",
        "Mango Grove",
        "Farmer's House",
        "Banyan Square",
        "Big House",
        "Morning Market",
        "Buffalo Fields",
        "Green Pasture",
        "Fern Hollow",
      ],
    },
    {
      name: "The Palm Village",
      lessons: [
        "Palm Corner",
        "Plough Fields",
        "Jackfruit Trees",
        "Cottage Yard",
        "Stone Seat",
        "Manor Gate",
        "Bazaar Lane",
        "Cattle Commons",
        "Hill Pasture",
        "Fern Slope",
      ],
    },
    {
      name: "The Well Village",
      lessons: [
        "Well Road",
        "Sowing Fields",
        "Fruit Garden",
        "Hearth House",
        "Tree Square",
        "Tiled House",
        "Spice Stalls",
        "Herd Meadow",
        "Wide Pasture",
        "Fern Bank",
      ],
    },
    {
      name: "The Harvest Village",
      lessons: [
        "Harvest Gate",
        "Golden Paddy",
        "Guava Grove",
        "Thatched Home",
        "Village Well",
        "Old Estate",
        "Fish Market",
        "Grazing Green",
        "Quiet Pasture",
        "Fern Field",
      ],
    },
    {
      name: "The Lamp Village",
      lessons: [
        "Lamp Road",
        "Bund Paths",
        "Papaya Patch",
        "Porch Steps",
        "Lamp Square",
        "Walled Garden",
        "Cloth Market",
        "Buffalo Wallow",
        "Evening Pasture",
        "Fern Dell",
      ],
    },
    {
      name: "The Coconut Village",
      lessons: [
        "Coconut Lane",
        "Water Channels",
        "Areca Grove",
        "Courtyard Home",
        "Gathering Tree",
        "Estate Lawn",
        "Coconut Market",
        "Goat Meadow",
        "Sunny Pasture",
        "Fern Glade",
      ],
    },
    {
      name: "The Rice Village",
      lessons: [
        "Rice Road",
        "Seedling Beds",
        "Cashew Grove",
        "Kitchen Garden",
        "Market Banyan",
        "Laterite Walls",
        "Pot Sellers",
        "Calf Meadow",
        "Long Pasture",
        "Fern Corner",
      ],
    },
    {
      name: "The Blossom Village",
      lessons: [
        "Blossom Path",
        "Flowering Fields",
        "Tamarind Grove",
        "Veranda House",
        "Stone Circle",
        "Garden Estate",
        "Flower Stalls",
        "Cow Fields",
        "Pasture Hill",
        "Fern Walk",
      ],
    },
    {
      name: "The Cart Village",
      lessons: [
        "Cart Track",
        "Threshing Ground",
        "Plantain Garden",
        "Hen House",
        "Crossroads Tree",
        "Estate Orchard",
        "Grain Market",
        "Open Commons",
        "Low Pasture",
        "Fern Rise",
      ],
    },
    {
      name: "The Morning Village",
      lessons: [
        "Sunrise Road",
        "Wet Paddies",
        "Lime Orchard",
        "Home Gate",
        "Shade Square",
        "Great House",
        "Sweet Stalls",
        "Grassy Commons",
        "Round Pasture",
        "Fern Patch",
      ],
    },
    {
      name: "The Bell Village",
      lessons: [
        "Bell Road",
        "Terrace Fields",
        "Pepper Garden",
        "Family House",
        "Meeting Tree",
        "Estate Steps",
        "Pottery Row",
        "Herd Grounds",
        "Far Pasture",
        "Fern Valley",
      ],
    },
    {
      name: "The Garden Village",
      lessons: [
        "Garden Gate",
        "Field Edges",
        "Orchard Walk",
        "Home Fields",
        "Centre Tree",
        "Estate Garden",
        "Weekly Market",
        "Cattle Green",
        "High Pasture",
        "Fern Trail",
      ],
    },
  ],
  // The Outer Fields: Back Road, Field Walls, Orchard Lane, Shrine Grove,
  // Farm Clearing, River Crossing, Estate Wall, Produce Route, Grazing Land,
  // Road Meadow.
  2: [
    {
      name: "The Orchard Road",
      lessons: [
        "Rear Lane",
        "Stone Fences",
        "Fruit Lane",
        "Little Shrine",
        "Farm Yard",
        "Stream Crossing",
        "Boundary Wall",
        "Harvest Road",
        "Herd Land",
        "Wayside Meadow",
      ],
    },
    {
      name: "The Far Fields",
      lessons: [
        "Far Lane",
        "Old Walls",
        "Mango Lane",
        "Shrine Tree",
        "Sunny Clearing",
        "Plank Bridge",
        "Long Wall",
        "Cart Route",
        "Grazing Hills",
        "Roadside Grass",
      ],
    },
    {
      name: "The Wall Fields",
      lessons: [
        "Hedge Road",
        "Laterite Fences",
        "Jackfruit Lane",
        "Lamp Shrine",
        "Barn Clearing",
        "Shallow Ford",
        "Estate Boundary",
        "Market Route",
        "Buffalo Land",
        "Meadow Bend",
      ],
    },
    {
      name: "The Shrine Fields",
      lessons: [
        "Quiet Lane",
        "Low Walls",
        "Cashew Lane",
        "Serpent Grove",
        "Hay Clearing",
        "River Bridge",
        "Garden Wall",
        "Basket Road",
        "Cow Land",
        "Flower Meadow",
      ],
    },
    {
      name: "The Bridge Fields",
      lessons: [
        "Side Road",
        "Field Borders",
        "Orchard Row",
        "Sacred Grove",
        "Grass Clearing",
        "Stepping Stones",
        "Tall Wall",
        "Carrying Road",
        "Meadow Herds",
        "Butterfly Meadow",
      ],
    },
    {
      name: "The Green Fields",
      lessons: [
        "Dusty Lane",
        "Wall Corners",
        "Guava Lane",
        "Grove Shrine",
        "Tool Clearing",
        "Wooden Bridge",
        "Mossy Wall",
        "Harvest Carts",
        "Grass Land",
        "Open Meadow",
      ],
    },
    {
      name: "The Stream Fields",
      lessons: [
        "Winding Lane",
        "Stone Rows",
        "Fruit Row",
        "Shrine Steps",
        "Well Clearing",
        "Stream Bridge",
        "Estate Corner",
        "Village Route",
        "Wide Grazing",
        "Breezy Meadow",
      ],
    },
    {
      name: "The Hedge Fields",
      lessons: [
        "Narrow Lane",
        "Crooked Walls",
        "Papaya Lane",
        "Tree Shrine",
        "Sheaf Clearing",
        "Clear Ford",
        "Wall Gate",
        "Produce Carts",
        "Grazing Slopes",
        "Clover Meadow",
      ],
    },
    {
      name: "The Sunny Fields",
      lessons: [
        "Morning Lane",
        "Walled Plots",
        "Tamarind Lane",
        "Lamp Grove",
        "Busy Clearing",
        "River Ford",
        "Estate Hedge",
        "Food Road",
        "Grazing Flats",
        "Wild Meadow",
      ],
    },
    {
      name: "The Quiet Fields",
      lessons: [
        "Shady Lane",
        "Field Stones",
        "Lime Lane",
        "Moss Shrine",
        "Rest Clearing",
        "Rushing Stream",
        "Grey Wall",
        "Fruit Carts",
        "Herd Hills",
        "Soft Meadow",
      ],
    },
    {
      name: "The Wide Fields",
      lessons: [
        "Old Byway",
        "Terrace Walls",
        "Blossom Lane",
        "Hidden Shrine",
        "Gate Clearing",
        "Water Crossing",
        "Estate Lane",
        "Trade Road",
        "Grazing Grounds",
        "Tall Grass",
      ],
    },
    {
      name: "The Farm Fields",
      lessons: [
        "Lane Behind",
        "Wall Path",
        "Grove Lane",
        "Shrine Clearing",
        "Field Clearing",
        "Cool River",
        "Estate Path",
        "Supply Road",
        "Grazing Commons",
        "Last Meadow",
      ],
    },
  ],
  // Village of Whispers: Village Road, Outer Houses, Village Lane, Banyan
  // Junction, Great Market, Temple Street, Playground, Quiet Houses, Edge
  // Gardens, Quiet Road.
  3: [
    {
      name: "The Temple Town",
      lessons: [
        "Town Road",
        "First Houses",
        "Town Lane",
        "Banyan Corner",
        "Grand Market",
        "Temple Lane",
        "Play Field",
        "Sleepy Houses",
        "Town Gardens",
        "Silent Road",
      ],
    },
    {
      name: "The Market Town",
      lessons: [
        "Market Road",
        "Edge Houses",
        "Crooked Lane",
        "Banyan Meeting",
        "Busy Bazaar",
        "Temple Walk",
        "Games Ground",
        "Still Houses",
        "Flower Gardens",
        "Calm Road",
      ],
    },
    {
      name: "The Lantern Town",
      lessons: [
        "Lantern Road",
        "Tiled Houses",
        "Lamp Lane",
        "Old Banyan",
        "Lantern Market",
        "Temple Gate",
        "Play Yard",
        "Resting Houses",
        "Herb Gardens",
        "Hushed Road",
      ],
    },
    {
      name: "The Busy Town",
      lessons: [
        "Busy Road",
        "Painted Houses",
        "Tight Lane",
        "Banyan Cross",
        "Market Square",
        "Bell Street",
        "Hopscotch Ground",
        "Shuttered Houses",
        "Bean Gardens",
        "Evening Road",
      ],
    },
    {
      name: "The Festival Town",
      lessons: [
        "Festival Road",
        "Bright Houses",
        "Garland Lane",
        "Banyan Shade",
        "Festival Market",
        "Drum Street",
        "Kite Field",
        "Dreaming Houses",
        "Jasmine Gardens",
        "Lamplit Road",
      ],
    },
    {
      name: "The Tile Town",
      lessons: [
        "Tile Road",
        "Red Houses",
        "Brick Lane",
        "Banyan Well",
        "Pot Market",
        "Shrine Street",
        "Marble Ground",
        "Closed Houses",
        "Back Gardens",
        "Soft Road",
      ],
    },
    {
      name: "The Shady Town",
      lessons: [
        "Shady Road",
        "Veranda Houses",
        "Cool Lane",
        "Banyan Benches",
        "Covered Market",
        "Flag Street",
        "Swing Tree",
        "Silent Houses",
        "Tulsi Gardens",
        "Hush Road",
      ],
    },
    {
      name: "The Mango Town",
      lessons: [
        "Mango Road",
        "Orchard Houses",
        "Mango Walk",
        "Banyan Circle",
        "Mango Market",
        "Offering Street",
        "Climbing Ground",
        "Siesta Houses",
        "Mango Gardens",
        "Sweet Road",
      ],
    },
    {
      name: "The Pepper Town",
      lessons: [
        "Pepper Road",
        "Spice Houses",
        "Pepper Lane",
        "Banyan Roots",
        "Spice Market",
        "Incense Street",
        "Chalk Ground",
        "Latched Houses",
        "Spice Gardens",
        "Wandering Road",
      ],
    },
    {
      name: "The Bell Town",
      lessons: [
        "Tower Road",
        "Gate Houses",
        "Bell Lane",
        "Banyan Bells",
        "Bell Market",
        "Chime Street",
        "Ring Games",
        "Quiet Porches",
        "Bell Gardens",
        "Echo Road",
      ],
    },
    {
      name: "The Old Town",
      lessons: [
        "Old Road",
        "Ancient Houses",
        "Old Lane",
        "Elder Banyan",
        "Old Market",
        "Old Temple",
        "Old Playground",
        "Sleeping Houses",
        "Old Gardens",
        "Faded Road",
      ],
    },
  ],
  // The Wild Crossing: Forest Edge, Shady Forest, Grass Hills, Hilltop
  // Meadow, River Descent, Wide Riverbank, Mangrove Island, River Woods,
  // Sunny Uplands, Green Road.
  4: [
    {
      name: "The River Journey",
      lessons: [
        "Woodland Edge",
        "Deep Shade",
        "Rolling Hills",
        "Hilltop Grass",
        "River Path",
        "Broad Riverbank",
        "Island Stop",
        "Riverside Woods",
        "Bright Uplands",
        "Green Lane",
      ],
    },
    {
      name: "The Long Crossing",
      lessons: [
        "Tree Line",
        "Dark Forest",
        "Grassy Slopes",
        "Summit Meadow",
        "River Steps",
        "Wide Water",
        "Mangrove Isle",
        "Streamside Woods",
        "Open Uplands",
        "Long Road",
      ],
    },
    {
      name: "The Forest Crossing",
      lessons: [
        "Forest Gate",
        "Cool Forest",
        "Windy Hills",
        "Hilltop Flowers",
        "Downhill Path",
        "Sandy Riverbank",
        "Middle Island",
        "Wet Woods",
        "Warm Uplands",
        "Grass Road",
      ],
    },
    {
      name: "The Island Crossing",
      lessons: [
        "Tree Edge",
        "Leafy Forest",
        "Soft Hills",
        "Hill Crest",
        "Riverward Path",
        "Pebble Bank",
        "Banyan Island",
        "River Forest",
        "Golden Uplands",
        "Meadow Road",
      ],
    },
    {
      name: "The Hill Crossing",
      lessons: [
        "Forest Border",
        "Quiet Forest",
        "Green Hills",
        "Top Meadow",
        "River Slope",
        "River Shore",
        "Little Island",
        "Mossy Woods",
        "High Uplands",
        "Far Road",
      ],
    },
    {
      name: "The Green Crossing",
      lessons: [
        "Wood's Edge",
        "Tall Forest",
        "Low Hills",
        "Breezy Hilltop",
        "Water Descent",
        "Reed Bank",
        "Tree Island",
        "Fern Woods",
        "Wide Uplands",
        "Bright Road",
      ],
    },
    {
      name: "The Wild River",
      lessons: [
        "Jungle Edge",
        "Hidden Forest",
        "Grass Ridges",
        "Hilltop View",
        "Bank Descent",
        "Muddy Riverbank",
        "Root Island",
        "Kingfisher Woods",
        "Sun Uplands",
        "Wild Road",
      ],
    },
    {
      name: "The Water Crossing",
      lessons: [
        "Shady Edge",
        "Hushed Forest",
        "Hill Tops",
        "Meadow Summit",
        "Riverbank Path",
        "Water's Edge",
        "Midstream Island",
        "Heron Woods",
        "Clear Uplands",
        "Open Road",
      ],
    },
    {
      name: "The Long River",
      lessons: [
        "Forest Fringe",
        "Old Forest",
        "Humpback Hills",
        "Hill Garden",
        "Stony Descent",
        "Calm Riverbank",
        "Mangrove Rest",
        "Deep Woods",
        "Sunlit Uplands",
        "Home Road",
      ],
    },
    {
      name: "The Deep Crossing",
      lessons: [
        "Wild Edge",
        "Thick Forest",
        "Rolling Grass",
        "Hilltop Rest",
        "River Walk",
        "Riverbank Trees",
        "Bridge Island",
        "Riverbank Woods",
        "Airy Uplands",
        "Green Trail",
      ],
    },
    {
      name: "The Far Crossing",
      lessons: [
        "Outer Woods",
        "Canopy Forest",
        "Tall Hills",
        "Hilltop Breeze",
        "River Trail",
        "Long Riverbank",
        "Island Milestone",
        "Evening Woods",
        "Quiet Uplands",
        "Onward Road",
      ],
    },
  ],
};
